# import pandas as pd
# import sqlite3 as sql

# conexao = sql.connect('bases-dengue')
# cursor = conexao.cursor()

# cursor.execute('''
#     CREATE TABLE bases_dengue_unificadas(
#     TP_NOT INT,
#     ID_AGRAVO VARCHAR,
#     DT_NOTIFIC DATE,
#     SEM_NOT INT,
#     NU_ANO INT,
#     SG_UF_NOT INT,
#     ID_MUNICIP INT,
#     ID_REGIONA VARCHAR,
#     ID_UNIDADE VARCHAR,
#     DT_SIN_PRI DATE,
#     SEM_PRI VARCHAR,
#     DT_NASC DATE,
#     NU_IDADE_N VARCHAR,
#     CS_SEXO VARCHAR,
#     CS_GESTANT VARCHAR,
#     CS_RACA VARCHAR,
#     CS_ESCOL_N VARCHAR,
#     SG_UF VARCHAR,
#     ID_MN_RESI VARCHAR,
#     ID_RG_RESI VARCHAR,
#     ID_PAIS VARCHAR,
#     DT_INVEST DATE,
#     ID_OCUPA_N VARCHAR,
#     FEBRE VARCHAR,
#     MIALGIA VARCHAR,
#     CEFALEIA VARCHAR,
#     EXANTEMA VARCHAR,
#     VOMITO VARCHAR,
#     NAUSEA VARCHAR,
#     DOR_COSTAS VARCHAR,
#     CONJUNTVIT VARCHAR,
#     ARTRITE VARCHAR,
#     ARTRALGIA VARCHAR,
#     PETEQUIA_N VARCHAR,
#     LEUCOPENIA VARCHAR,
#     LACO VARCHAR,
#     DOR_RETRO VARCHAR,
#     DIABETES VARCHAR,
#     HEMATOLOG VARCHAR,
#     HEPATOPAT VARCHAR,
#     RENAL VARCHAR,
#     HIPERTENSA VARCHAR,
#     ACIDO_PEPT VARCHAR,
#     AUTO_IMUNE VARCHAR,
#     DT_CHIK_S1 DATE,
#     DT_CHIK_S2 DATE,
#     DT_PRNT DATE,
#     RES_CHIKS1 VARCHAR,
#     RES_CHIKS2 VARCHAR,
#     RESUL_PRNT VARCHAR,
#     DT_SORO DATE,
#     RESUL_SORO VARCHAR,
#     DT_NS1 DATE,
#     RESUL_NS1 VARCHAR,
#     DT_VIRAL DATE,
#     RESUL_VI_N VARCHAR,
#     DT_PCR DATE,
#     RESUL_PCR_ VARCHAR,
#     SOROTIPO VARCHAR,
#     HISTOPA_N VARCHAR,
#     IMUNOH_N VARCHAR,
#     HOSPITALIZ VARCHAR,
#     DT_INTERNA DATE,
#     UF VARCHAR,
#     MUNICIPIO VARCHAR,
#     TPAUTOCTO VARCHAR,
#     COUFINF VARCHAR,
#     COPAISINF VARCHAR,
#     COMUNINF VARCHAR,
#     CLASSI_FIN VARCHAR,
#     CRITERIO VARCHAR,
#     DOENCA_TRA VARCHAR,
#     CLINC_CHIK VARCHAR,
#     EVOLUCAO VARCHAR,
#     DT_OBITO DATE,
#     DT_ENCERRA DATE,
#     ALRM_HIPOT VARCHAR,
#     ALRM_PLAQ VARCHAR,
#     ALRM_VOM VARCHAR,
#     ALRM_SANG VARCHAR,
#     ALRM_HEMAT VARCHAR,
#     ALRM_ABDOM VARCHAR,
#     ALRM_LETAR VARCHAR,
#     ALRM_HEPAT VARCHAR,
#     ALRM_LIQ VARCHAR,
#     DT_ALRM DATE,
#     GRAV_PULSO VARCHAR,
#     GRAV_CONV VARCHAR,
#     GRAV_ENCH VARCHAR,
#     GRAV_INSUF VARCHAR,
#     GRAV_TAQUI VARCHAR,
#     GRAV_EXTRE VARCHAR,
#     GRAV_HIPOT VARCHAR,
#     GRAV_HEMAT VARCHAR,
#     GRAV_MELEN VARCHAR,
#     GRAV_METRO VARCHAR,
#     GRAV_SANG VARCHAR,
#     GRAV_AST VARCHAR,
#     GRAV_MIOC VARCHAR,
#     GRAV_CONSC VARCHAR,
#     GRAV_ORGAO VARCHAR,
#     DT_GRAV DATE,
#     MANI_HEMOR VARCHAR,
#     EPISTAXE VARCHAR,
#     GENGIVO VARCHAR,
#     METRO VARCHAR,
#     PETEQUIAS VARCHAR,
#     HEMATURA VARCHAR,
#     SANGRAM VARCHAR,
#     LACO_N VARCHAR,
#     PLASMATICO VARCHAR,
#     EVIDENCIA VARCHAR,
#     PLAQ_MENOR VARCHAR,
#     CON_FHD VARCHAR,
#     COMPLICA VARCHAR,
#     TP_SISTEMA VARCHAR,
#     NDUPLIC_N VARCHAR,
#     CS_FLXRET VARCHAR,
#     FLXRECEBI VARCHAR,
#     ANO_NASC VARCHAR,
#     DT_DIGITA DATE,
#     MIGRADO_W VARCHAR,
#     diferenca_dias FLOAT
# )
#                ''')

# # Passo 3: Ler o arquivo CSV usando pandas
# banco_dengue = pd.read_csv('C:\Users\Lua.LUADESKTOP\Documents\Luana\Projetos\Pesquisa CNPQ\estudo-dengue\db\tratamento\banco_dengue_unificado.csv')  # Substitua pelo caminho real do seu arquivo CSV

# # Passo 4: Inserir os dados do DataFrame na tabela SQLite
# banco_dengue.to_sql('bases_dengue_unificadas', conexao, if_exists='append', index=False)

# # Passo 5: Commit e fechar a conexão
# conexao.commit()
# conexao.close()